name: release
on:
  push:
    branches-ignore: ["*"]
    tags: ["*"]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: version
      run: |
        VERSION=$(echo ${GITHUB_REF} | awk -F/ '{print $3}')
        echo "::set-env name=VERSION::${VERSION}"
    - name: build
      run: docker build -t convox/convox:${VERSION} .
    - name: login
      run: docker login --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}"
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: push
      run: docker push convox/convox:${VERSION}
    # - name: build
    #   run: docker build -t docker.pkg.github.com/convox/convox/convox:${VERSION} .
    # - name: push
    #   run: docker login docker.pkg.github.com --username convox --password "${GITHUB_TOKEN}"
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # - name: push
    #   run: docker push docker.pkg.github.com/convox/convox/convox:${VERSION}
